apiVersion: v1
data:
  firebaseconfig: |-
    #{firebaseconfig}#
kind: ConfigMap
metadata:
  name: firebaseconfig
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: gograph
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gograph
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '4000'
      labels:
        app: gograph 
    spec:
      nodeSelector:
        name: ambrose2
      containers:
        - name: gograph
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 4000
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "200M"
          env:
          - name: FIREBASE_ADMIN
            valueFrom:
              configMapKeyRef:
                name: "firebaseconfig"
                key: "firebaseconfig"
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: gograph
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: NodePort
  ports:
    - nodePort: 30001
      targetPort: 4000
      port: 4000
      protocol: TCP
  selector:
    app: gograph