// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Abilities struct {
	IsHidden *bool    `json:"IsHidden,omitempty"`
	Slot     *int     `json:"Slot,omitempty"`
	Ability  *Ability `json:"Ability,omitempty"`
}

type Ability struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type Forms struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type GameIndices struct {
	GameIndex *int     `json:"GameIndex,omitempty"`
	Version   *Version `json:"Version,omitempty"`
}

type HeldItems struct {
	VersionDetails []*VersionDetails `json:"version_details,omitempty"`
	Item           *Item             `json:"item,omitempty"`
}

type Item struct {
	Name *string `json:"name,omitempty"`
	URL  *string `json:"url,omitempty"`
}

type Move struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type MoveLearnMethod struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type Moves struct {
	VersionGroupDetails []*VersionGroupDetails `json:"VersionGroupDetails,omitempty"`
	Move                *Move                  `json:"Move,omitempty"`
}

type Pokemon struct {
	BaseExperience         *int           `json:"BaseExperience,omitempty"`
	Height                 *int           `json:"Height,omitempty"`
	ID                     *int           `json:"ID,omitempty"`
	IsDefault              *bool          `json:"IsDefault,omitempty"`
	LocationAreaEncounters *string        `json:"LocationAreaEncounters,omitempty"`
	Name                   *string        `json:"Name,omitempty"`
	Order                  *int           `json:"Order,omitempty"`
	Weight                 *int           `json:"Weight,omitempty"`
	Types                  []*Types       `json:"Types,omitempty"`
	Stats                  []*Stats       `json:"Stats,omitempty"`
	Sprites                *Sprites       `json:"Sprites,omitempty"`
	Species                *Species       `json:"Species,omitempty"`
	Moves                  []*Moves       `json:"Moves,omitempty"`
	HeldItems              []*HeldItems   `json:"HeldItems,omitempty"`
	GameIndices            []*GameIndices `json:"GameIndices,omitempty"`
	Forms                  []*Forms       `json:"Forms,omitempty"`
	Abilities              []*Abilities   `json:"Abilities,omitempty"`
}

type Species struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type Sprites struct {
	BackDefault      *string `json:"BackDefault,omitempty"`
	BackFemale       *string `json:"BackFemale,omitempty"`
	BackShiny        *string `json:"BackShiny,omitempty"`
	BackShinyFemale  *string `json:"BackShinyFemale,omitempty"`
	FrontDefault     *string `json:"FrontDefault,omitempty"`
	FrontFemale      *string `json:"FrontFemale,omitempty"`
	FrontShiny       *string `json:"FrontShiny,omitempty"`
	FrontShinyFemale *string `json:"FrontShinyFemale,omitempty"`
}

type Stat struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type Stats struct {
	BaseStat *int  `json:"BaseStat,omitempty"`
	Effort   *int  `json:"Effort,omitempty"`
	Stat     *Stat `json:"Stat,omitempty"`
}

type Type struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type Types struct {
	Slot *int  `json:"Slot,omitempty"`
	Type *Type `json:"Type,omitempty"`
}

type Version struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type VersionDetails struct {
	Rarity  *int     `json:"rarity,omitempty"`
	Version *Version `json:"version,omitempty"`
}

type VersionGroup struct {
	Name *string `json:"Name,omitempty"`
	URL  *string `json:"URL,omitempty"`
}

type VersionGroupDetails struct {
	LevelLearnedAt  *int             `json:"LevelLearnedAt,omitempty"`
	VersionGroup    *VersionGroup    `json:"VersionGroup,omitempty"`
	MoveLearnMethod *MoveLearnMethod `json:"MoveLearnMethod,omitempty"`
}
