apiVersion: v1
data:
  firebaseConfig: |-
    #{firebaseConfig}#
kind: ConfigMap
metadata:
  name: firebaseConfig
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jsgraph
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsgraph
  template:
    metadata:
      labels:
        app: jsgraph 
    spec:
      containers:
        - name: jsgraph
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 4000
              protocol: TCP
          imagePullPolicy: Always
          nodeSelector:
            name: ambrose4
          resources:
            limits:
              cpu: "500m"
              memory: "400M"
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/app/db/credential.json"
          volumeMounts:
          - name: "firebaseConfig"
            mountPath: "/app/db/credential.json"
      volumes:
      - configmap:
        name: "firebaseConfig" 
        items:
        - key: "firebaseConfig"
          path: "/app/db/credential.json"
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: jsgraph
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      targetPort: 4000
      port: 4000
      protocol: TCP
  selector:
    app: jsgraph