apiVersion: v1
data:
  firebaseconfig: |-
    #{firebaseconfig}#
kind: ConfigMap
metadata:
  name: firebaseconfig
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: jsgraph
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsgraph
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/data/metrics'
        prometheus.io/port: '80'
      labels:
        app: jsgraph 
    spec:
      nodeSelector:
        name: ambrose4
      containers:
        - name: jsgraph
          image: #{deployment.image.name}#
          ports:
            - name: http-api
              containerPort: 4000
              protocol: TCP
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "300m"
              memory: "200M"
          env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/app/db/creds/credential.json"
          volumeMounts:
          - name: "firebaseconfig"
            mountPath: "/app/db/creds"
      volumes:
      - name: "firebaseconfig" 
        configMap:
          name: "firebaseconfig"
          items:
          - key: "firebaseconfig"
            path: "./credential.json"
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
---
kind: Service
apiVersion: v1
metadata:
  name: jsgraph
  namespace: prod
  labels:
    version: 0.1.203643-1
spec:
  type: NodePort
  ports:
    - nodePort: 30000
      targetPort: 4000
      port: 4000
      protocol: TCP
  selector:
    app: jsgraph